version: "3.8"
services:
  steamcmd:
    image: cm2network/steamcmd
    container_name: 7days-server
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
    environment:
      - GAMEPARAMS="+force_install_dir /data +login anonymous +app_update 294420 +quit" # Replace with desired game parameters
      - PUID=1000 # Replace with your user ID
      - PGID=1000 # Replace with your group ID
    volumes:
      - ./servers/7days:/home/steam/serverfiles
    restart: unless-stopped